services:
  taxi_fare_predictor:
    image: lixuanlin/taxi-fare-predictor
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64