name: dsci522_group
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.15
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - altair==5.4.1
      - anyio==4.6.2.post1
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - black==24.10.0
      - bleach==6.2.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - debugpy==1.8.8
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - fonttools==4.55.0
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - idna==3.10
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.29.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.28
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mypy-extensions==1.0.0
      - narwhals==1.14.1
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pluggy==1.5.0
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - protobuf==5.28.3
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==18.0.0
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.21.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==1.4.46
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - tenacity==9.0.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tomli==2.1.0
      - tornado==6.4.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - vegafusion==1.6.9
      - vegafusion-python-embed==1.6.9
      - vl-convert-python==1.7.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
