name: dsci522_group_conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - sqlalchemy
  - pandas
  - matplotlib
  - altair>=5.0.0  # Explicitly specify version
  - numpy
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - jupyterlab
  - python-dotenv
  - requests
  - pyarrow
  - vega_datasets  # Added for Altair examples
  - pip:
    - plotly
    - pytest
    - black
    - nbformat
    - vegafusion
    - vegafusion-python-embed
    - vl-convert-python