name: dsci522_group_conda
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.11
 - conda=23.9.0
 - pip=24.3.1
 - ipykernel=6.29.5
 - sqlalchemy=2.0.36
 - matplotlib=3.9.2
 - altair=5.5.0
 - numpy=2.1.3
 - scikit-learn=1.5.2
 - scipy=1.14.1
 - seaborn=0.13.2
 - statsmodels=0.14.4
 - jupyterlab=4.3.1
 - python-dotenv=1.0.1
 - requests=2.32.3
 - vega_datasets=0.9.0
 - pandas=2.2.3
 - pyarrow==18.1.0
 - tabulate=0.9.0
 - quarto=1.5.57
 - pip:
   - plotly==5.24.1
   - pytest==8.3.3
   - black==24.10.0
   - nbformat==5.10.4
   - vegafusion==2.0.1
   - vegafusion-python-embed==1.6.9
   - vl-convert-python==1.7.0
   - pandera==0.21.0
  #  - tabulate==0.9.0
  #  - quarto-cli==1.5.57