name: dsci522_group
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - ipykernel
  - sqlalchemy==1.4.46
  - pandas==2.1.4
  - matplotlib
  - altair
  - numpy>=1.24.0
  - scikit-learn>=1.2.0
  - scipy>=1.10.0
  - seaborn>=0.12.0
  - statsmodels>=0.14.0
  - jupyterlab
  - python-dotenv
  - requests
  - pip
  - pip:
    - plotly>=5.13.0
    - pytest>=7.1.0
    - black>=23.0
    - nbformat>=5.7.0