<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Han Wang, Jam Lin, Jiayi Li, Yibin Long">

<title>NYC Taxis Fare Prediction Analysis Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="yellow_taxi_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="yellow_taxi_analysis_files/libs/quarto-html/quarto.js"></script>
<script src="yellow_taxi_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="yellow_taxi_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="yellow_taxi_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="yellow_taxi_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="yellow_taxi_analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="yellow_taxi_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="yellow_taxi_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="yellow_taxi_analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#preface" id="toc-preface" class="nav-link active" data-scroll-target="#preface"><span class="header-section-number">1</span> Preface</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">2</span> Summary</a></li>
  <li><a href="#introduction-background" id="toc-introduction-background" class="nav-link" data-scroll-target="#introduction-background"><span class="header-section-number">3</span> Introduction &amp; Background</a></li>
  <li><a href="#analysis-question" id="toc-analysis-question" class="nav-link" data-scroll-target="#analysis-question"><span class="header-section-number">4</span> Analysis Question</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset"><span class="header-section-number">5</span> Dataset</a></li>
  <li><a href="#methods-results" id="toc-methods-results" class="nav-link" data-scroll-target="#methods-results"><span class="header-section-number">6</span> Methods &amp; Results</a>
  <ul class="collapse">
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">6.1</span> Methods</a></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda"><span class="header-section-number">6.2</span> EDA</a></li>
  <li><a href="#modeling" id="toc-modeling" class="nav-link" data-scroll-target="#modeling"><span class="header-section-number">6.3</span> Modeling</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">6.4</span> Results</a></li>
  </ul></li>
  <li><a href="#limitations-next-steps" id="toc-limitations-next-steps" class="nav-link" data-scroll-target="#limitations-next-steps"><span class="header-section-number">7</span> Limitations &amp; Next Steps</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8</span> References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">NYC Taxis Fare Prediction Analysis Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Han Wang, Jam Lin, Jiayi Li, Yibin Long </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="preface" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="preface"><span class="header-section-number">1</span> Preface</h2>
<p>This report was developed as a deliverable for the term project in DSCI 522 (Data Science Workflows), a course in the Master of Data Science program at the University of British Columbia.</p>
<p>The overall objective of this project was to automate a typical data science workflow. This report summarizes the results of a series of automated Python scripts that handle tasks such as data retrieval, data cleaning, exploratory data analysis (EDA), creation of a predictive machine learning model, and interpretation of the results. The report provides a detailed explanation of each step, applying it to the specific context of the dataset in question. It assumes the reader has a basic understanding of machine learning terminology and concepts.</p>
</section>
<section id="summary" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="summary"><span class="header-section-number">2</span> Summary</h2>
<p>This report presents a linear regression model developed to predict NYC taxi fare amount. Using data from 30,000 taxi trips in January 2024, we build a linear regression model using trip distance feature, with each additional mile increasing the fare by approximately $3.54. The model was evaluated using a test dataset, where predicted fare amounts were compared to actual fares. While the model performed well overall, some outliers were identified, suggesting the need for further data cleaning and additional features to improve accuracy. Future steps include incorporating more features, experimenting with other regression models like KNN and Lasso regression, and addressing hyperparameters for better generalizability and performance.</p>
</section>
<section id="introduction-background" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="introduction-background"><span class="header-section-number">3</span> Introduction &amp; Background</h2>
<p>Taking a taxi in New York City can be overwhelming for first-time visitors, especially for tourists unfamiliar with the city’s layout and fare system. With over 200,000 taxi trips taking place daily, yellow cabs remain an essential mode of transportation for both locals and visitors. However, the lack of transparency often leads to concerns among tourists about overcharging or being taken on unnecessarily long routes.</p>
<p>To address these concerns, we use data from 30,000 Yellow Taxi trips recorded in January 2024, provided by the NYC Taxi and Limousine Commission (TLC). Our analysis examines how to predict taxi fare amounts, offering valuable insights to help tourists better understand what they should expect to pay for a taxi ride in NYC. By leveraging data-driven analysis, we aim to provide a clearer and more predictable fare structure, enabling tourists to make more informed decisions during their travels in the city.</p>
</section>
<section id="analysis-question" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="analysis-question"><span class="header-section-number">4</span> Analysis Question</h2>
<p>How do we best predict NYC yellow taxi fare amounts?</p>
</section>
<section id="dataset" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="dataset"><span class="header-section-number">5</span> Dataset</h2>
<p>The data set used in this project is the TLC Trip Record Data, which includes taxi and for-hire vehicle trip records collected by technology providers authorized under the Taxicab &amp; Livery Passenger Enhancement Programs (TPEP/LPEP). This data is sourced from the NYC Taxi and Limousine Commission (TLC) and can be accessed from the [NYC Taxi and Limousine Commission’s website]<span class="citation" data-cites="nyctlc2024">(<a href="#ref-nyctlc2024" role="doc-biblioref">Taxi and Commission 2024</a>)</span>(https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page). Yellow and green taxi trip records contain fields capturing pick-up and drop-off dates and times, pick-up and drop-off locations, trip distances, itemized fares, rate types, payment types, and driver-reported passenger counts. Similarly, For-Hire Vehicle (FHV) trip records include fields such as dispatching base license number, pick-up date and time, and taxi zone location ID. It is important to note that the TLC did not create this data and makes no representations regarding its accuracy. FHV trip records are based on submissions from dispatching bases and may not represent the total volume of trips. Additionally, the TLC reviews these records and enforces necessary actions to improve their accuracy and completeness.</p>
</section>
<section id="methods-results" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="methods-results"><span class="header-section-number">6</span> Methods &amp; Results</h2>
<section id="methods" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="methods"><span class="header-section-number">6.1</span> Methods</h3>
<p>In order to address our research question, we will begin by selecting the appropriate features from the dataset through exploratory data analysis (EDA) and by consulting the data dictionary to better understand the instances within the dataset. Since this is a linear regression modeling problem, we will use the LinearRegression model as our model of choice. Linear regression is a fundamental and widely used method for predictive modeling. The dataset used in this study includes daily fare amounts and trip distance data from January 2024, covering 30,000 observations. The data will be split into training and test sets, with 70% allocated for training and 30% for testing.</p>
<p>The analysis will be conducted using the Python programming language <span class="citation" data-cites="Python">(<a href="#ref-Python" role="doc-biblioref">Van Rossum and Drake 2009</a>)</span>, with the following Python packages: numpy <span class="citation" data-cites="harris2020array">(<a href="#ref-harris2020array" role="doc-biblioref">Harris et al. 2020</a>)</span>, pandas <span class="citation" data-cites="pandas">(<a href="#ref-pandas" role="doc-biblioref">McKinney 2010</a>)</span>, scikit-learn <span class="citation" data-cites="pedregosa2011scikit">(<a href="#ref-pedregosa2011scikit" role="doc-biblioref">Pedregosa et al. 2011</a>)</span>, and altair <span class="citation" data-cites="altair">(<a href="#ref-altair" role="doc-biblioref">VanderPlas 2018</a>)</span>.</p>
</section>
<section id="eda" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="eda"><span class="header-section-number">6.2</span> EDA</h3>
<p>Lets do some data validation by checking the target variable fare_amount’s distribution:</p>
<div id="fig-density" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../charts/Fare_Amount_Density_Chart.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Fare Amount Density Chart
</figcaption>
</figure>
</div>
<p>Based on <a href="#fig-density" class="quarto-xref">Figure&nbsp;1</a>, we see that most values of the fare amount make sense - they are mostly under $50, with a cluster of fare amounts at around 65 USD, likely a longer trip from the airport. However, we see fare amounts that are lower that 0 which are not explained by the documentation, that “The time-and-distance fare calculated by the meter.” They might be simply refunded trips, but since we cannot confirm, we will choose to drop rows where the fare amount is negative.</p>
<p>We’ll split the dataset into training set and test set.</p>
<p>Now, we’ll perform a summary of the data set that is relevant for exploratory data analysis related to our regression analysis. We’ll check out the summary statistics for each column in the dataset.</p>
<div class="cell" data-execution_count="1">
<div id="tbl-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="1">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Data Set Summary
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="4">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">VendorID</th>
<th style="text-align: left;">tpep_pickup_datetime</th>
<th style="text-align: left;">tpep_dropoff_datetime</th>
<th style="text-align: right;">passenger_count</th>
<th style="text-align: right;">trip_distance</th>
<th style="text-align: right;">RatecodeID</th>
<th style="text-align: right;">PULocationID</th>
<th style="text-align: right;">DOLocationID</th>
<th style="text-align: right;">payment_type</th>
<th style="text-align: right;">fare_amount</th>
<th style="text-align: right;">extra</th>
<th style="text-align: right;">mta_tax</th>
<th style="text-align: right;">tip_amount</th>
<th style="text-align: right;">tolls_amount</th>
<th style="text-align: right;">improvement_surcharge</th>
<th style="text-align: right;">total_amount</th>
<th style="text-align: right;">congestion_surcharge</th>
<th style="text-align: right;">Airport_fee</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">20720</td>
<td style="text-align: left;">20720</td>
<td style="text-align: left;">20720</td>
<td style="text-align: right;">19690</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">19690</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">20720</td>
<td style="text-align: right;">19690</td>
<td style="text-align: right;">19690</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.74976</td>
<td style="text-align: left;">2024-01-17 00:46:01.533832</td>
<td style="text-align: left;">2024-01-17 01:01:38.636196</td>
<td style="text-align: right;">1.3387</td>
<td style="text-align: right;">3.19747</td>
<td style="text-align: right;">2.03403</td>
<td style="text-align: right;">166.394</td>
<td style="text-align: right;">165.39</td>
<td style="text-align: right;">1.13436</td>
<td style="text-align: right;">18.5866</td>
<td style="text-align: right;">1.48258</td>
<td style="text-align: right;">0.49527</td>
<td style="text-align: right;">3.37729</td>
<td style="text-align: right;">0.525144</td>
<td style="text-align: right;">0.999628</td>
<td style="text-align: right;">27.3619</td>
<td style="text-align: right;">2.31061</td>
<td style="text-align: right;">0.143448</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">2024-01-01 00:06:10</td>
<td style="text-align: left;">2024-01-01 00:10:03</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">2024-01-09 16:07:26.750000</td>
<td style="text-align: left;">2024-01-09 16:26:42.250000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8.6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15.48</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">2024-01-17 10:28:41</td>
<td style="text-align: left;">2024-01-17 10:46:02</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.68</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">162</td>
<td style="text-align: right;">163</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12.8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">20.16</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">2024-01-24 17:47:47</td>
<td style="text-align: left;">2024-01-24 18:01:19.500000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">234</td>
<td style="text-align: right;">236</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">20.5</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">4.2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">28.6</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: left;">2024-01-31 23:56:14</td>
<td style="text-align: left;">2024-02-01 00:15:56</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">68.48</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">265</td>
<td style="text-align: right;">265</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">600</td>
<td style="text-align: right;">11.75</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">62.75</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">601</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">1.75</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.434275</td>
<td style="text-align: left;">nan</td>
<td style="text-align: left;">nan</td>
<td style="text-align: right;">0.844332</td>
<td style="text-align: right;">4.31842</td>
<td style="text-align: right;">9.65642</td>
<td style="text-align: right;">63.626</td>
<td style="text-align: right;">69.4664</td>
<td style="text-align: right;">0.527717</td>
<td style="text-align: right;">17.8768</td>
<td style="text-align: right;">1.79912</td>
<td style="text-align: right;">0.0549392</td>
<td style="text-align: right;">3.8067</td>
<td style="text-align: right;">2.09673</td>
<td style="text-align: right;">0.0190096</td>
<td style="text-align: right;">22.1385</td>
<td style="text-align: right;">0.66147</td>
<td style="text-align: right;">0.480072</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Based on the summary statistics in <a href="#tbl-summary" class="quarto-xref">Table&nbsp;1</a>, for the fare amount, the mean fare amount is 18.59 USD, while the median is 12.8 USD, which again points to a right-skewed distribution for this column. This confirms what we saw with the density chart.</p>
<p>Next, we’ll create a correlation plot of all of the columns against one another, to check out the strength and direction of associations between columns.</p>
<div id="fig-correlation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../charts/Correlation_Plot_Train_Spearman.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Correlation Plot
</figcaption>
</figure>
</div>
<p>Based on <a href="#fig-correlation" class="quarto-xref">Figure&nbsp;2</a>, we see that “trip_distance” and “fare_amount” have a fairly high positive correlation, which may indicate that they are fairly positively associated with each other. We decide now to use “trip_distance” to try and predict “fare_amount”. Since there are no null values in “trip_distance”, no null values need to be dropped for “trip_distance”.</p>
</section>
<section id="modeling" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="modeling"><span class="header-section-number">6.3</span> Modeling</h3>
<p>As discussed in the Methods summary, we will now build and test our Linear Regression Model.</p>
<p>The regression line formula is: y_hat = 3.62 * trip_distance + 7.02</p>
<p>Finally, let’s calculate some error metrics and perform a visualization of the result of the regression model in the form of a scatter plot with the regression line.</p>
<div class="cell" data-execution_count="3">
<div id="tbl-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Regression Performance Metrics
</figcaption>
<div aria-describedby="tbl-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">RMSE</td>
<td style="text-align: right;">6.78282</td>
</tr>
<tr class="even">
<td style="text-align: left;">R²</td>
<td style="text-align: right;">0.848052</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MAE</td>
<td style="text-align: right;">3.23701</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div id="fig-error" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../charts/Pred_Vs_Actual.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Predicted vs Actual Taxi Fare Amounts With Error Line
</figcaption>
</figure>
</div>
<p>Lastly in <a href="#fig-predictions" class="quarto-xref">Figure&nbsp;4</a>, here is the regression line for the predictions.</p>
<div id="fig-predictions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-predictions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../charts/Final_Linear_Regression.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-predictions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Regression of Trip Distance vs Fare Amount for NYC Yellow Taxis in January 2024
</figcaption>
</figure>
</div>
</section>
<section id="results" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="results"><span class="header-section-number">6.4</span> Results</h3>
<p>The objective of the analysis was to predict the fare amount using a linear regression model. The regression plot, generated from the model, demonstrates a positive linear relationship between trip distance and fare amount for NYC Yellow Taxis in January 2024. This confirms that as the trip distance increases, the fare amount also increases, as expected.</p>
<p>The linear regression model shows moderate predictive power with an R-squared value of 0.85, which explains about high percent of fare variance. The low MAE of 3.24 USD indicates good accuracy for typical rides, although the higher RMSE (6.78 USD) suggests sensitivity to outliers. The visual analysis of the errors reveals the model performs best for the 10-50 USD range, and underestimates fares over 100 USD. The actual NYC taxi fare is calculated through initial fare, per-mile charge, and additional fees for peak hours, nighttime, tolls, etc that this model cannot predict, but can be built further using more complicated multilinear regression or ML models.</p>
<p>Based on the estimated result from the regression line formula derived from the model, this suggests that for each additional mile traveled, the fare increases by approximately 3.62 USD, and the base fare (when the trip distance is zero) is around 7.02 USD.</p>
<p>To evaluate the model’s predictive performance, we applied it to the test data, which was split from the original dataset (70 percent training, 30 percent testing). The predicted fare amounts were compared against the actual fare amounts in the test set. The predicted values were calculated using the formula derived from the model, where trip distances from the test set were used as input to generate the corresponding fare predictions.</p>
<p>A scatter plot of the actual fare amounts versus trip distances, along with the regression line, was generated to visualize the results. The plot showed that the model fits most of the data well, but there were some outliers where the predicted fare deviated significantly from the actual values. These discrepancies could be due to errors or special cases in the fare data.</p>
</section>
</section>
<section id="limitations-next-steps" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="limitations-next-steps"><span class="header-section-number">7</span> Limitations &amp; Next Steps</h2>
<p>Overall, our model may be useful in the initial analysis of tourists interested in making informal predictions about NYC taxi fare amounts. However, there are several areas where this work can be improved. In this analysis, we did not include hyperparameters like the regularization parameter (α), which is essential for controlling overfitting and improving model generalizability. Furthermore, the model currently uses only a single feature (trip distance), which may result in underfitting and bias. In the next steps, we plan to incorporate more features into the model and refine the approach to improve its precision and predictive power. Additionally, experimenting with other regression models, such as KNN regression for non-linear relationships and Lasso regression for linear relationships, could be valuable to see if these models improve performance.</p>
</section>
<section id="references" class="level2 unnumbered" data-number="8">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">8 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-harris2020array" class="csl-entry" role="listitem">
Harris, Charles R, K Jarrod Millman, Stéfan J Van Der Walt, Ralf Gommers, Pauli Virtanen, David Cournapeau, Eric Wieser, et al. 2020. <span>“Array Programming with NumPy.”</span> <em>Nature</em> 585 (7825): 357–62.
</div>
<div id="ref-pandas" class="csl-entry" role="listitem">
McKinney, Wes. 2010. <span>“Data Structures for Statistical Computing in Python.”</span> In <em>Proceedings of the 9th Python in Science Conference</em>, edited by Stéfan van der Walt and Jarrod Millman, =51–56.
</div>
<div id="ref-pedregosa2011scikit" class="csl-entry" role="listitem">
Pedregosa, Fabian, Gaël Varoquaux, Alexandre Gramfort, Vincent Michel, Bertrand Thirion, Olivier Grisel, Mathieu Blondel, et al. 2011. <span>“Scikit-Learn: Machine Learning in Python.”</span> <em>The Journal of Machine Learning Research</em> 12: 2825–30.
</div>
<div id="ref-nyctlc2024" class="csl-entry" role="listitem">
Taxi, New York City, and Limousine Commission. 2024. <span>“TLC Trip Record Data.”</span> <a href="https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page" class="uri">https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page</a>.
</div>
<div id="ref-Python" class="csl-entry" role="listitem">
Van Rossum, Guido, and Fred L. Drake. 2009. <em>Python 3 Reference Manual</em>. Scotts Valley, CA: CreateSpace.
</div>
<div id="ref-altair" class="csl-entry" role="listitem">
VanderPlas, Jake. 2018. <span>“Altair: Interactive Statistical Visualizations for Python.”</span> <em>Journal of Open Source Software</em> 3 (7825, 32): 1057. <a href="https://doi.org/10.21105/joss.01057">https://doi.org/10.21105/joss.01057</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>