data_path: "data/raw/yellow_tripdata_2024-01.csv"  # Change as needed
delimiter: ","                                  # Applicable only for CSV files
expected_columns:
  - "VendorID"
  - "tpep_pickup_datetime"
  - "tpep_dropoff_datetime"
  - "passenger_count"
  - "trip_distance"
  - "RatecodeID"
  - "store_and_fwd_flag"
  - "PULocationID"
  - "DOLocationID"
  - "payment_type"
  - "fare_amount"
  - "extra"
  - "mta_tax"
  - "tip_amount"
  - "tolls_amount"
  - "improvement_surcharge"
  - "total_amount"
  - "congestion_surcharge"
  - "Airport_fee"
correlation_thresholds:
  feature_label: 0.9
  feature_feature: 0.8
